[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.2"
  NPM_VERSION = "10.2.4"

[dev]
  command = "npm run dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove the conflicting redirects that interfere with Next.js routing
# Next.js and the Netlify Next.js plugin handle routing automatically
